export const receitas = {
  entrada: [
    {
      nome: "Batata Frita com Queijo Cremoso e Calabresa",
      ingredientes: [
        "2 sacos de batata pré-frita congelada ou 8 batatas grandes",
        "1 calabresa cortada em cubos",
        "200 g de bacon cortado em cubos",
        "1 copo de requeijão",
        "1 pacote pequeno de queijo ralado",
        "200 g de mussarela ou queijo pato",
        "1/4 de xícara de leite",
        "Salsinha e cebolinha a gosto",
        "Sal a gosto",
      ],
      modo_preparo: [
        "Frite a batata, escorra bem em papel toalha e coloque em uma travessa.",
        "Coloque um pouco de sal.",
        "Frite a calabresa e o bacon. Escorra bem e reserve.",
        "Coloque em uma panela o requeijão, o queijo ralado, o queijo mussarela ou prato grosseiramente picado e o leite.",
        "Mexa em fogo baixo até o queijo derreter e obter um creme liso.",
        "Despeje o queijo cremoso na batata, espalhe a calabresa e o bacon frito e salpique salsinha e cebolinha a gosto.",
      ],
      id_video: "MkZ7lM7iaiE",
      tempo: "40 min",
      porcao: 4,
      por: "Taize",
      img: "batata",
      tipo: "entrada",
    },
    {
      nome: "Pão Caseiro Fácil",
      ingredientes: [
        "Pão adocicado",
        "1 kg de farinha de trigo sem fermento (reserve 1 xícara ou 120 g, só use-a se for necessário)",
        "400 ml de leite morno",
        "2 ovos (remova a película ou pele da gema)",
        "45 g de fermento biológico fresco ou 3 tabletes de 15 g cada (em temperatura ambiente)",
        "Dica: você pode substituir o fermento biológico fresco por 15 g de fermento seco para pães - não use fermento para bolos",
        "100 ml de óleo",
        "1 xícara de açúcar (200 g)",
        "1/2 colher (sopa) de sal",
        "Dica: se preferir pão salgado, leia as informações adicionais ao final da receita",
      ],
      modo_preparo: [
        "Em um liquidificador, coloque todos os ingredientes, menos o sal e a farinha (o sal mata o fermento).",
        "Bata até obter uma consistência líquida, cremosa e espumosa (cuidado com a temperatura do leite, pois ele deve estar morno e não quente; se estiver quente, ele matará o seu fermento).",
        "Despeje esse líquido em uma bacia e adicione metade da farinha e misture com uma colher de pau.",
        "A massa ficará mole e grudenta.",
        "Reserve 1 xícara de farinha e adicione o resto dela à massa junto com o sal.",
        "A massa ficará macia e um pouco pegajosa.",
        "Nesse momento, ligue seu forno em fogo baixo por 5 minutos e desligue-o.",
        "Os pães serão colocados nele para que o calor os faça crescer, enquanto descansam.",
        "Enfarinhe uma superfície e sove a massa com carinho até que ela desgrude das mãos.",
        "Só em último caso, adicione o restante da farinha: isso deixará o pão mais leve e fofo.",
        "Experimente e corrija o sabor da massa conforme seu paladar.",
        "Divida a massa em duas partes iguais e abra cada uma com um rolo, enfarinhando a superfície novamente: neste momento a massa ficará macia e lisa.",
        "Unte com um pouquinho de óleo ou margarina a uma forma de bolo média de 30 x 24 ou duas formas próprias para pão de 27 x 11 (prefiro forma para pães, pois o pão cresce bonito e para para cima)",
        "Enrole os pães no tamanho da forma escolhida e faça pequenos cortes em “X” em cima da massa para decorar.",
        "Leve os pães ao forno que você aqueceu por 5 minutos e desligou.",
        "Deixe-os descansar, para que cresçam, estimulados pelo calor morno.",
        "Cuidado: se o forno estiver muito quente, seus pães vão assar antes de crescer e a massa ficará embatumada.",
        "Aguarde uns 20 a 30 minutos e, se tudo correr bem, ela crescerá lisa e arredondada, podendo até ultrapassar as bordas da forma.",
        "Se ela não crescer, não se preocupe.",
        "Mesmo que a massa não tenha crescido após esse tempo, ligue o forno em temperatura média (180º C) e deixe ela assar por uns 30, 40 ou 45 minutos (depende do seu forno).",
        "O fermento 'preguiçoso' poderá 'despertar' à força nesse momento.",
        "Quando sentir o cheirinho de pão assado, aumente um pouco chama do fogo para que a casca escureça.",
        "Se deixar por muito tempo, ela ficará amarga.",
        "Deixe esfriar dentro ou fora do forno.",
        "O pão deverá estar leve, fofo, cheio de furinhos (aerado), delicado, cheiroso e quase desmanchando quando cortado.",
      ],
      id_video: "nLjB7mz5JFE",
      tempo: "120 min",
      porcao: 2,
      por: "Carlos Silva",
      img: "pao",
      tipo: "entrada",
    },
    {
      nome: "Bolinho de Arroz",
      ingredientes: [
        "2 xícaras (chá) de arroz cozido",
        "1/2 xícara (chá) de queijo ralado",
        "1/2 xícara (chá) de leite",
        "2 colheres (sopa) de cheiro-verde picado",
        "1 colher (sopa) de fermento em pó",
        "1/2 xícara (chá) de amido de milho",
        "1/2 xícara (chá) de farinha de trigo",
        "3 ovos",
        "Óleo para fritar",
      ],
      modo_preparo: [
        "Em um recipiente, misture todos os ingredientes até criar uma massa firme e encorpada.",
        "Molde os bolinhos e frite-os no óleo quente, até que fiquem dourados.",
        "Escorra sobre papel absorvente.",
      ],
      id_video: "IAWhCuprwko",
      tempo: "30 min",
      porcao: 30,
      por: "Tania Cione",
      img: "bolinho",
      tipo: "entrada",
    },
    {
      nome: "Salada Caesar",
      ingredientes: [
        "1 alface americana lavada, higienizada e picada grosseiramente",
        "1 peito de frango sem osso, temperado, grelhado e picado em tiras (opcional)",
        "1 xícara de parnesão ralado grosseiramente",
        "2 xícaras de croutons bem crocantes (feitos com pão de forma sem casca)",
        "Molho:",
        "1/2 xícara de óleo (milho, canola ou girasol)",
        "1/2 xícara de azeite de boa qualidade",
        "1 gema",
        "2 dentes de alho amassados",
        "5 filés de anchovas",
        "2 colheres de sopa de maionese caseira",
        "1 colher de sopa mostarda",
        "1 colher de sopa de suco de limão",
      ],
      modo_preparo: [
        "Molho:",
        "Coloque todos os ingredientes no liquidificador, bata bem pouco, somente para unir os ingredientes, se bater demais irá virar uma maionese.",
        "Arrume a alface em uma saladeira funda, coloque o frango em tiras (opcional) e regue com o molho, polvilhe o parmesão.",
        "Cubra com os croutons somente na hora de servir para não amolecer.",
        "Acompanhado de um bom bife à milanesa não há quem resista.",
        "É uma refeição completa",
        "Obs: O molho é feito com a gema crua, mas para os mis impressionados poderá ser utilizada a gema do ovo cozido e frio.",
      ],
      id_video: "3JxdhkpOrC0",
      tempo: "15 min",
      porcao: 4,
      por: "Paula Freire",
      img: "salada",
      tipo: "entrada",
    },
    {
      nome: "Cebola Empanada",
      ingredientes: [
        "1 cebola grande",
        "1 ovo",
        "1 xícara de leite integral ",
        "1 xícara de farinha de trigo",
        "3 colheres (sopa) de fubá",
        "Temperos",
        "1 colher (chá) de páprica picante",
        "1 colher (chá) de páprica defumada",
        "1 colher (chá) de cominho em pó",
        "1 colher (chá) de tomilho",
        "1 colher (chá) de pimenta-do-reino ",
        "1/2 colher (chá) de açafrão",
        "Sal a gosto",
        "Óleo",
      ],
      modo_preparo: [
        "Junte a farinha de trigo com sal, tomilho, cominho e pimenta.",
        "Junte o fubá e misture tudo.",
        "Em outro recipiente misture o ovo com o leite.",
        "Reserve os dois recipientes e comece a cortar a cebola",
        "Retire as duas pontas da cebola.",
        "Faça um corte maior em uma das pontas para que se forme uma base fixa.",
        "Retire a casca por completo com cuidado.",
        "Apoie a cebola com esse pedaço para baixo e comece a fazer os outros cortes.",
        "Corte ao meio, mas não passe a faca até o final, deixe 2 cm entre a base e o final do corte.",
        "Faça isso em todos os cortes seguintes: comece no meio, faça uma cruz, depois corte um x entre a cruz e finalize com mais dois cortes.",
        "O ideal é que ela pareça com fatias de pizza do mesmo tamanho.",
        "Coloque água bem gelada em um recipiente e coloque a cebola com os cortes para baixo. ",
        "Leve isso para à geladeira por duas horas.",
        "Retire da geladeira e mergulhe a cebola na mistura de leite e ovo (passe bastante no meio dos cortes).",
        "Misture os temperos à farinha de trigo e ao fubá",
        "Passe a cebola na farinha e faça o mesmo processo, com cuidado para tudo ficar empanado. Leve à geladeira por mais 10 minutos para a primeira camada firmar.",
        "Repita o mesmo processo de ovo e farinha.",
        "Coloque uma panela de óleo para esquentar que caiba a cebola, de modo que ela fique em pé.",
        "Frite a cebola até dourar.",
      ],
      id_video: "bg4xnXhuPlo",
      tempo: "120 min",
      porcao: 1,
      por: "Tudo Gostoso",
      img: "cebola",
      tipo: "entrada",
    },
  ],
  principal: [
    {
      nome: "Bife à Parmegiana",
      ingredientes: [
        "Bife:",
        "1 kg de carne para bife",
        "3 dentes de alho",
        "Sal",
        "1 ovo",
        "Farinha de rosca",
        "Óleo",
        "Molho:",
        "1/2 cebola picada",
        "1 lata de molho de tomate",
        "1 colher (sobremesa) de catchup",
        "1 colher (chá) de mostarda",
        "Salsinha e cebolinha a gosto",
        "Sal a gosto",
        "Óleo",
        "Montagem:",
        "Queijo mussarela",
        "Orégano",
      ],
      modo_preparo: [
        "Bife:",
        "Tempere os bifes com alho e sal e reserve.",
        "Bata o ovo inteiro e passe os bifes pelo ovo e pela farinha de rosca.",
        "Aqueça em uma frigideira o óleo e frite os bifes, escorra-os em papel-toalha e vá dispondo em um refratário.",
        "Molho:",
        "Refogue a cebola no óleo, junte o molho de tomate, o catchup, a mostarda, o sal, salsinha e cebolinha, abaixe o fogo e deixe o molho apurar.",
        "Montagem:",
        "Despeje o molho pronto sobre os bifes e distribua queijo mussarela sobre os bifes",
        "Salpique delicadamente um pouco de orégano por cima do queijo e leve ao forno até derreter o queijo.",
        "Sirva com arroz e purê de batatas.",
        "Bom apetite.",
      ],
      id_video: "tZuDfGGBVl8",
      tempo: "90 min",
      porcao: 6,
      por: "Juliana",
      img: "bifeParmegiana",
      tipo: "principal",
    },
    {
      nome: "Rocambole de Carne Moída",
      ingredientes: [
        "1/2 kg de carne moída",
        "1 pacote de sopa de cebola",
        "Presunto fatiado",
        "Queijo fatiado",
        "Tempero verde",
        "Sal a gosto",
      ],
      modo_preparo: [
        "Tempere a carne moída com a sopa de cebola, o tempero verde e o sal.",
        "Coloque a carne temperada sobre uma folha de papel laminado ou papel manteiga e abra a massa com um rolo, na espessura de 1 cm, mais ou menos.",
        "Forre a carne com o presunto e o queijo, pode-se colocar também milho verde, ervilha e requeijão.",
        "Enrole a carne, com ajuda da folha de papel laminado ou manteiga, em forma de rocambole.",
        "Leve ao forno, em temperatura alta, por mais ou menos 30 minutos, ou no microondas por 15 minutos.",
        "Bom apetite!",
      ],
      id_video: "NmICuanRLck",
      tempo: "15 min",
      porcao: 8,
      por: "Luciere",
      img: "rocambole",
      tipo: "principal",
    },
    {
      nome: "Escondidinho de Carne Seca",
      ingredientes: [
        "1 kg de mandioca cozida",
        "1 lata de creme de leite com soro",
        "2 colheres de margarina",
        "1/2 kg de carne-seca dessalgada e cozida",
        "1 cebola média picadinha",
        "4 dentes de alho esmagados",
        "2 tomates sem casca e picados",
        "Sal e pimenta a gosto",
        "Queijo ralado a gosto",
      ],
      modo_preparo: [
        "Esprema a mandioca ainda quente e leve em uma panela com a margarina e sal.",
        "Quando estiverem bem misturados acrescente o creme de leite, misture e reserve.",
        "Refogue a cebola e o alho em um fio de azeite.",
        "Acrescente a carne-seca desfiada e deixe fritar um pouco.",
        "Acrescente os tomates e deixe cozinhar até ficarem murchos e acerte o sal se achar necessário.",
        "Em um refratário untado com azeite, coloque uma camada do purê de mandioca, a carne seca e termine com o restante do purê.",
        "Polvilhe com queijo parmesão ralado e leve ao forno pra gratinar.",
      ],
      id_video: "XNKtlKOCQLg",
      tempo: "60 min",
      porcao: 6,
      por: "Juliana da Graça",
      img: "escondidinho",
      tipo: "principal",
    },
    {
      nome: "Costelinha com Molho Barbecue (Outback)",
      ingredientes: [
        "2 kg costelinhas de porco aferventadas em água quente",
        "Molho:",
        "1 colher (sopa) óleo",
        "2 colheres (sopa) cebola picada",
        "1/2 xícara (chá) açúcar mascavo",
        "1/2 xícara (chá) vinagre branco",
        "2 colheres (sopa) molho inglês",
        "2 xícaras (chá) catchup",
        "1 folha de louro",
        "1 colher (sopa) chilli em pó",
        "1/2 xícara (chá) água",
        "Sal e pimenta do reino a gosto",
      ],
      modo_preparo: [
        "Espalhe sal por toda a carne e coloque para ferver por 10 minutos em um panela com bastante água quente.",
        "Escorra a água, arrume as costelinhas em uma assadeira, cubra com papel alumínio e leve ao forno baixo ( 180º) por 40 minutos.",
        "Em uma panela, refogue a cebola no óleo, acrescente o açúcar mascavo e o vinagre e deixe o açúcar dissolver.",
        "Acrescente o molho inglês, o catchup, o louro, o chilli em pó e a água e cozinhe por 30 minutos em fogo baixo ou até o molho engrossar.",
        "Tempere com sal e pimenta-do-reino, coe e reserve.",
        "Após os 40 minutos retire as costelinhas do forno, retire o papel alumínio e pincele com o molho.",
        "Aumente a temperatura do forno, asse as costelinhas por mais 10 minutos, pincele novamente com o molho, asse mais 5 minutos e repita mais uma vez esta operação.",
        "Sirva com mais molho à parte.",
      ],
      id_video: "oCz9dAq3l2Q",
      tempo: "70 min",
      porcao: 5,
      por: "Rodrigo Mendes",
      img: "costelinha",
      tipo: "principal",
    },
    {
      nome: "Yakisoba da Casa",
      ingredientes: [
        "300 g de espaguete",
        "1 cebola grande cortada em pedaços médios",
        "1 colher (sopa) de óleo",
        "1/2 maço pequeno de brócolis",
        "1/2 maço pequeno de couve-flor",
        "10 colheres (sopa) de molho shoyu",
        "400 g de carne cortada em tiras",
        "100 g de champignon",
        "1 cenoura cortada em rodelas",
        "250 ml de água",
        "1 colher (sopa) de amido de milho, dissolvido em 50 ml de água",
        "Acelga a gosto",
      ],
      modo_preparo: [
        "Cozinhe o macarrão em ponto al dente e reserve.",
        "Em uma panela, adicione o azeite, a cebola, a carne e refogue bem.",
        "Adicione o molho shoyu e cozinhe por 3 minutos em fogo médio.",
        "Acrescente mais água, aguarde levantar fervura e adicione o amido de milho.",
        "Mexa até engrossar, abaixe o fogo e adicione o champignon, a couve-flor, o brócolis e a cenoura.",
        "Cozinhe por 8 minutos e acrescente, por último, a acelga e o macarrão.",
        "Misture bem, acerte o sal e tampe a panela por mais 1 minuto.",
        "Está pronto para servir!",
      ],
      id_video: "E3Kvegx7XeY",
      tempo: "40 min",
      porcao: 4,
      por: "Tudo Gostoso",
      img: "yakissoba",
      tipo: "principal",
    },
  ],
  sobremesa: [
    {
      nome: "Bombom de Travessa",
      ingredientes: [
        "250g de chocolate ao leite.",
        "250g de chocolate meio amargo.",
        "2 latas de leite condensado.",
        "2 latas de creme de leite.",
        "2 colheres de margarina.",
        "2 caixas de morango.",
      ],
      modo_preparo: [
        "Coloque as latas de leite condensado em uma panela com a manteiga e faça uma massa como um brigadeiro mole.",
        "Coloque em uma travessa e, por cima deste brigadeiro mole, coloque os morangos cortados ao meio.",
        "Reserve para fazer a cobertura.",
        "Para fazer a cobertura, rale o chocolate ao leite e o meio amargo e misture ao creme de leite.",
        "Misture e coloque no micro-ondas durante 1 minuto.",
        "Retire e mexa.",
        "Coloque de novo no micro-ondas por mais 1 minuto.",
        "Despeje a cobertura por cima dos morangos e leve à geladeira coberta por papel-filme.",
      ],
      id_video: "T1YQicI16Fk",
      tempo: "35 min",
      porcao: 10,
      por: "Laura",
      img: "bombomTravessa",
      tipo: "sobremesa",
    },
    {
      nome: "Danoninho Caseiro",
      ingredientes: [
        "1 lata de leite condensado",
        "2 caixas de creme de leite",
        "200 g de iogurte natural",
        "1 pacote de suco em pó sabor morango",
      ],
      modo_preparo: [
        "Em um liquidificador, bata todos os ingrediente até obter uma consistência cremosa.",
        "Dispense a mistura em um recipiente e leve à geladeira até que esteja firme. ",
      ],
      id_video: "NA9_DLru0Bk",
      tempo: "10 min",
      porcao: 4,
      por: "Cristiane Russell Seixas",
      img: "danoninhoCaseiro",
      tipo: "sobremesa",
    },
    {
      nome: "Bolo de Sorvete",
      ingredientes: [
        "Primeira calda:",
        "2 xícaras (chá) de açúcar",
        "1 xícara (chá) de água",
        "Segunda calda:",
        "5 colheres (sopa) de água",
        "2 colheres (sopa) de achocolatado",
        "Sorvete:",
        "1 lata de leite condensado",
        "2 latas de leite (use a lata do leite condensado para medir)",
        "4 gemas peneiradas",
        "4 claras batidas em neve",
        "5 colheres (sopa) de açúcar",
        "1 lata de creme de leite sem soro",
      ],
      modo_preparo: [
        "Primeira calda:",
        "Queimar o açúcar, quando estiver derretido acrescente a água.",
        "Deixe derreter o caramelo, até obter uma calda bem grossa.",
        "Passe em uma forma de buraco e leve ao freezer.",
        "Segunda calda:",
        "Misture os ingredientes numa vasilha e depois de desenformado cubra o sorvete com esta calda.",
        "Sorvete:",
        "Leve ao fogo o leite, o leite condensado e as gemas, até engrossar.",
        "Deixe esfriar.",
        "Bata as claras em neve e acrescente o açúcar.",
        "Junte o creme de leite e creme de gemas já frio.",
        "Misture tudo e despeje na fôrma que está no freezer.",
        "Volte ao freezer, no momento de servir, passe a forma ao fogo e desenforme como se fosse um pudim.",
      ],
      id_video: "MP0nq1FNk1c",
      tempo: "60 min",
      porcao: 10,
      por: "Fernanda",
      img: "boloSorvete",
      tipo: "sobremesa",
    },
    {
      nome: "Pave Simples de Chocolate",
      ingredientes: [
        "1 lata de creme de leite",
        "1 lata de leite (a mesma medida da lata de creme de leite)",
        "2 latas de leite condensado",
        "2 gemas",
        "2 colheres de maisena",
        "3 colheres de chocolate em pó ou achocolatado",
        "Biscoito maisena",
        "Leite para molhar os biscoitos",
        "Raspas de chocolate (opcional)",
        "Manteiga sem sal ou margarina, só para dar o ponto",
      ],
      modo_preparo: [
        "Primeiro, pegue a lata de leite condensado, as gemas, a maisena e o leite.",
        "Coloque no fogo e deixe até que fique um creme, reserve.",
        "Coloque a segunda lata de leite condensado com um pouco de margarina e o chocolate.",
        "Deixe no fogo até ficar um creme tipo brigadeiro.",
        "Desligue o fogo e junte com o creme de leite.",
        "MONTAGEM",
        "Coloque primeiro o creme branco.",
        "Em seguida, mergulhe os biscoitos no leite e coloque sobre o creme branco.",
        "Depois, coloque o creme preto e acrescente as raspas de chocolate sobre ele.",
        "Deixe no congelador durante 2 horas.",
      ],
      id_video: "1ngCIWqIxtI",
      tempo: "140 min",
      porcao: 8,
      por: "Laíze Leopoldina",
      img: "paveChocolate",
      tipo: "sobremesa",
    },
    {
      nome: "Mousse de Limão Rápido",
      ingredientes: [
        "1 lata de leite condensado",
        "1 lata de creme de leite",
        "1/2 copo (americano) de suco puro de limão",
        "Bis de limão",
      ],
      modo_preparo: [
        "No liquidificador, bata o leite condensado e o creme de leite por 3 minutos.",
        "Acrescente aos poucos o suco de limão e continue batendo.",
        "Despeje o mousse em um refratário e leve à geladeira.",
        "Na hora de servir, triture o bis e coloque por cima do mousse para decorar.",
      ],
      id_video: "4ELOqMupksA",
      tempo: "10 min",
      porcao: 8,
      por: "Dah Gabi",
      img: "mousseLimao",
      tipo: "sobremesa",
    },
  ],
  vegano: [
    {
      nome: "Crepioca - Pão de Queijo de Frigideira",
      ingredientes: [
        "1 ovo",
        "2 colheres (sopa) de tapioca",
        "1 colher (sopa) requeijão light",
        "1 pitada de sal",
      ],
      modo_preparo: [
        "Coloque todos os ingredientes em um prato e misture-os até que fiquem homogêneos.",
        "Depois, aqueça um pouquinho uma frigideira sem óleo, sem azeite e sem manteiga, somente a frigideira e logo após coloque a massa.",
        "Espere um tempo até que ela fique um pouco douradinha embaixo, se preferir virar a crepioca, vire-a com a ajuda de uma colher ou garfo.",
        "Ou coloque uma tampa que cubra toda a frigideira e espere ela cozinhar até o ponto do seu gosto, mais queimadinho ou mais branquinho.",
      ],
      id_video: "EbmEtfd43ro",
      tempo: "6 min",
      porcao: 1,
      por: "Natália Souza Brito",
      img: "crepioca",
      tipo: "vegano",
    },
    {
      nome: "Tabule",
      ingredientes: [
        "45 g de trigo para kibe",
        "200 g de tomate picado sem sementes",
        "1 cebola picada",
        "2 pepinos picados",
        "1 maço de salsinha picada",
        "3 colheres (sopa) de suco de limão",
        "2 colheres (sopa) de azeite",
        "sal e pimenta-do-reino a gosto",
        "1/4 colher (chá) de noz-moscada",
        "Hortelã picada",
        "Salsa picada",
      ],
      modo_preparo: [
        "Em um recipiente, deixe o trigo de molho por 2 horas.",
        "Lave bem o trigo em água corrente, escorra e esprema nas mão para retirar o excesso de umidade.",
        "Passe a cebola picada em água fria e escorra bem.",
        "Junte os outros ingredientes (menos o tomate) e deixe tampado na geladeira por pelo menos 8 horas.",
        "Acrescente os tomates na hora de servir.",
      ],
      id_video: "O3SW3EnMQZ0",
      tempo: "480 min",
      porcao: 4,
      por: "Tudo Gostoso",
      img: "tabule",
      tipo: "vegano",
    },
    {
      nome: "Salada de Tomate Cereja com Queijo e Maçã",
      ingredientes: [
        "2 xícaras de tomate cereja cortados ao meio",
        "1 xícara de queijo minas frescal light cortado em cubos",
        "1 maçã pequena com casca picada em cubos",
        "Cheiro-verde picado a gosto",
        "Suco de 1 limão",
        "Azeite de oliva a gosto",
        "Sal a gosto",
      ],
      modo_preparo: [
        "Misturar os tomates e a maçã.",
        "Colocar os temperos, o queijo frescal e o cheiro verde.",
        "Misturar delicadamente.",
      ],
      id_video: "VxawKK4ogb4",
      tempo: "20 min",
      porcao: 4,
      por: "Gilberto Damas",
      img: "saladaTomate",
      tipo: "vegano",
    },
    {
      nome: "Pão de Batata sem Glúten",
      ingredientes: [
        "2 batatas grandes",
        "Água fervendo",
        "1 tablete de fermento biológico",
        "1 colher (sopa) rasa de açúcar",
        "1 ovo",
        "50 g de manteiga",
        "Sal a gosto",
        "1/2 xícara (chá) de leite",
        "2 xícaras (chá) de fécula de batata",
        "Manteiga para untar",
        "1 gema para pincelar o pão",
      ],
      modo_preparo: [
        "Corte superficialmente a casca das batatas",
        "Coloque-as em uma panela com água fervendo, até cobrir.",
        "Cozinhe até ficarem macias",
        "Em seguida, descasque as batatas e amasse-as.",
        "Em uma tigela à parte, acrescente 1 tablete de fermento biológico.",
        "Misture até ficar líquido.",
        "Adicione o ovo, a manteiga, o sal, a batata amassada e o leite.",
        "Misture bem e acrescente a fécula de batata.",
        "Misture com as mãos até formar uma massa homogênea.",
        "Unte duas formas com manteiga e coloque a massa.",
        "Cubra com um pano e deixe a massa descansar por 30 minutos.",
        "Em seguida, pincele a massa com gema e leve ao forno (180° C) por cerca de 30 minutos.",
      ],
      id_video: "S2NUadlXNK0",
      tempo: "60 min",
      porcao: 2,
      por: "Tudo Gostoso",
      img: "paoBatata",
      tipo: "vegano",
    },
    {
      nome: "Pão sem Glúten com Farinha de Arroz",
      ingredientes: [
        "2 ovos",
        "4 colheres (sopa) de azeite ou óleo de sua preferência",
        "1 copo de iogurte (pode ser normal, desnatado ou sem lactose)",
        "1 colher (sopa) de açúcar ou adoçante forno e fogão",
        "1 colher (chá) de sal",
        "1 e 1/2 xícara de farinha de arroz integral (pode ser a normal também)",
        "1 colher (sopa) de fermento químico (o mesmo que se usa para bolos)",
      ],
      modo_preparo: [
        "Coloque todos os ingredientes na ordem dos ingredientes no liquidificador, exceto o fermento e bata bem.",
        "Coloque o fermento por último e misture delicadamente até incorporar à massa.",
        "Despeje em uma forma untada e enfarinhada e coloque no forno preaquecido a 18° C, por 40 minutos.",
      ],
      id_video: "kjBwMLfkL8U",
      tempo: "40 min",
      porcao: 6,
      por: "Sheyla Campos Cardoso",
      img: "paoSemGluten",
      tipo: "vegano",
    },
  ],
};
